apiVersion: v1
kind: Service
metadata:
  name: integration-api
  namespace: integration-staging
  labels:
    app: integration-api
spec:
  type: ClusterIP
  selector:
    app: integration-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
